# netlify.toml

# Redirects and headers are inherited by all deploys,
# including production, branch deploys, and Deploy Previews.

# The following headers are required for ffmpeg.wasm to work correctly
# by enabling SharedArrayBuffer.